
-- Create products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  images TEXT[], -- Array of image URLs
  tags TEXT[], -- Array of tags (e.g., 'best_seller')
  sizes TEXT[], -- Array of sizes (e.g., 'P', 'M', 'G', 'GG')
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create banners table
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image TEXT NOT NULL,
  title TEXT,
  subtitle TEXT,
  button_text TEXT,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;

-- Create policies (adjust as needed for your security model)
-- Allow public read access
CREATE POLICY "Public products are viewable by everyone" ON products FOR SELECT USING (true);
CREATE POLICY "Public banners are viewable by everyone" ON banners FOR SELECT USING (true);

-- Allow authenticated (or anon for now if you want to allow admin via API) insert/update/delete
-- Note: For a real app, you'd restrict this to authenticated admin users.
-- For this demo with a custom admin panel, we might need to allow anon write if we use the anon key on the server,
-- OR use the service_role key on the server (which is safer but I don't have it).
-- Given I only have the ANON key, I must allow anon writes for the admin panel to work via the client,
-- OR I rely on the server to handle it. But the server also only has the anon key unless I was given the service key.
-- Wait, the user provided SUPABASE_ANON_KEY.
-- So I must allow anon inserts/updates for the admin panel to work.
CREATE POLICY "Enable insert for anon" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for anon" ON products FOR UPDATE USING (true);
CREATE POLICY "Enable delete for anon" ON products FOR DELETE USING (true);

CREATE POLICY "Enable insert for anon" ON banners FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable delete for anon" ON banners FOR DELETE USING (true);
